name: memory_mitra
description: "MemoryMitra — a gentle companion for every memory. An AI-based cognitive gaming and memory assistance prototype for elderly dementia patients in India's North Eastern Region."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  connectivity_plus: ^7.3.1
  http: ^1.2.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^18.0.1
  flutter_dotenv: ^5.2.1
  audioplayers: ^6.1.0
  lottie: ^3.1.0
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
    - assets/audio/
    - assets/animations/
    - assets/videos/
    - assets/videos/procedural_test.mp4
    - assets/videos/washing_clothes.mp4
    - assets/videos/splash_screen.mp4



  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
