name: memory_mitra
description: "MemoryMitra — a gentle companion for every memory. An AI-based cognitive gaming and memory assistance prototype for elderly dementia patients in India's North Eastern Region."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  connectivity_plus: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
