import 'package:flutter/foundation.dart';

import '../models/daily.dart';
import '../models/game.dart';
import '../models/memory_fragment.dart';

/// Where an answer came from. Surfaced to the caregiver so an AI-written
/// sentence is never mistaken for a clinical measurement.
enum AiSource {
  /// Generated by Gemini.
  gemini,

  /// Generated by the fine-tuned Llama model, running locally via llama.cpp
  /// — real generated language, still fully offline.
  onDeviceLlm,

  /// Produced on the device from rule-based templates, with no network and no
  /// model at all. The final fallback: works before any model download, and
  /// on devices too old/low-memory to run one.
  onDevice,
}

extension AiSourceX on AiSource {
  String get label => switch (this) {
        AiSource.gemini => 'AI-generated',
        AiSource.onDeviceLlm => 'Generated on this device (offline AI)',
        AiSource.onDevice => 'Generated on this device',
      };
}

/// Why an AI call could not be answered.
///
/// Every one of these is expected in normal operation — a patient in rural
/// Assam will hit [offline] far more often than [server] — so callers are
/// given a specific kind rather than a thrown exception to inspect.
enum AiErrorKind {
  /// No route to the network, or the caregiver switched the app offline.
  offline,

  /// The request outlived its deadline.
  timeout,

  /// No API key or proxy URL was configured for this build.
  notConfigured,

  /// The provider rejected the key or the quota is spent.
  unauthorized,

  /// Too many requests.
  rateLimited,

  /// The provider returned 5xx, or the response could not be reached.
  server,

  /// A reply arrived but was not the shape we asked for.
  malformed,

  /// A reply arrived and contained nothing usable.
  empty,

  /// The model declined to answer (safety filters).
  blocked,

  /// This platform has no direct HTTP transport — see `ai_transport.dart`.
  unsupportedPlatform,

  unknown,
}

extension AiErrorKindX on AiErrorKind {
  /// Caregiver-facing wording. Never blames the user, never shows a stack.
  String get message => switch (this) {
        AiErrorKind.offline =>
          'No connection right now. Showing what this device worked out on its own.',
        AiErrorKind.timeout => 'That took too long to come back. Please try again.',
        AiErrorKind.notConfigured =>
          'AI insights are not set up in this build.',
        AiErrorKind.unauthorized => 'AI insights are not authorised for this build.',
        AiErrorKind.rateLimited => 'Too many requests just now. Please try again shortly.',
        AiErrorKind.server => 'The insight service is unavailable. Please try again later.',
        AiErrorKind.malformed => 'That reply could not be read. Please try again.',
        AiErrorKind.empty => 'No answer came back. Please try again.',
        AiErrorKind.blocked => 'That question cannot be answered here.',
        AiErrorKind.unsupportedPlatform =>
          'Direct AI calls are not available on this platform.',
        AiErrorKind.unknown => 'Something went wrong. Please try again.',
      };

  /// Whether trying the same request again could plausibly succeed.
  bool get isRetryable => switch (this) {
        AiErrorKind.timeout ||
        AiErrorKind.rateLimited ||
        AiErrorKind.server ||
        AiErrorKind.offline ||
        AiErrorKind.empty ||
        AiErrorKind.unknown =>
          true,
        AiErrorKind.notConfigured ||
        AiErrorKind.unauthorized ||
        AiErrorKind.malformed ||
        AiErrorKind.blocked ||
        AiErrorKind.unsupportedPlatform =>
          false,
      };
}

@immutable
class AiFailure {
  const AiFailure(this.kind, {this.detail});

  final AiErrorKind kind;

  /// Developer-facing detail. Never rendered to a patient or caregiver.
  final String? detail;

  String get message => kind.message;
  bool get isRetryable => kind.isRetryable;

  @override
  String toString() => 'AiFailure(${kind.name}${detail == null ? '' : ': $detail'})';
}

/// The outcome of an AI call: an answer, or a reason there is none.
///
/// A sealed result rather than exceptions, because "no connection" is an
/// ordinary state for this app and every caller has to render it.
sealed class AiResult<T> {
  const AiResult();

  bool get isSuccess => this is AiSuccess<T>;

  T? get valueOrNull => switch (this) {
        AiSuccess<T>(:final T value) => value,
        AiError<T>() => null,
      };

  AiFailure? get failureOrNull => switch (this) {
        AiSuccess<T>() => null,
        AiError<T>(:final AiFailure failure) => failure,
      };

  R fold<R>({
    required R Function(T value) onSuccess,
    required R Function(AiFailure failure) onError,
  }) =>
      switch (this) {
        AiSuccess<T>(:final T value) => onSuccess(value),
        AiError<T>(:final AiFailure failure) => onError(failure),
      };
}

class AiSuccess<T> extends AiResult<T> {
  const AiSuccess(this.value);
  final T value;
}

class AiError<T> extends AiResult<T> {
  const AiError(this.failure);

  AiError.of(AiErrorKind kind, {String? detail})
      : failure = AiFailure(kind, detail: detail);

  final AiFailure failure;

  AiErrorKind get kind => failure.kind;
}

/// A reading of how the patient is doing, written for the caregiver.
///
/// Deliberately framed as *activity performance*, never as a diagnosis — the
/// same constraint the rest of the app holds to.
@immutable
class CognitiveInsight {
  const CognitiveInsight({
    required this.summary,
    required this.strengths,
    required this.attentionAreas,
    required this.recommendedActivity,
    required this.recommendedDifficulty,
    required this.reason,
    required this.evidence,
    required this.source,
    required this.generatedAt,
  });

  /// Two or three plain sentences about the recent period.
  final String summary;

  /// What is going well, in the caregiver's language.
  final List<String> strengths;

  /// What is slipping. Phrased as observation, never as prognosis.
  final List<String> attentionAreas;

  final GameId recommendedActivity;

  /// 1–5, matching `AdaptiveDifficultyService`'s scale.
  final int recommendedDifficulty;

  /// Why this activity at this level — the explainable part.
  final String reason;

  /// The concrete signals behind the recommendation, so a caregiver can check
  /// the reasoning rather than take it on trust.
  final List<String> evidence;

  final AiSource source;
  final DateTime generatedAt;

  CognitiveInsight copyWith({AiSource? source}) => CognitiveInsight(
        summary: summary,
        strengths: strengths,
        attentionAreas: attentionAreas,
        recommendedActivity: recommendedActivity,
        recommendedDifficulty: recommendedDifficulty,
        reason: reason,
        evidence: evidence,
        source: source ?? this.source,
        generatedAt: generatedAt,
      );
}

/// What the patient was asking about. Used to pick a fallback answer when the
/// model is unreachable, and to keep the assistant on its rails.
enum AssistantIntent {
  /// "What do I have today?"
  schedule,

  /// "What activity should I do?"
  activity,

  /// "What are my reminders?" / "Have I taken my medicine?"
  reminders,

  /// "Who is Priya?" — people in the profile.
  people,

  /// "Where am I?" / "What day is it?"
  orientation,

  /// A warm exchange with no informational content.
  companionship,

  /// Mitra invited, or gently reoffered, a life story — the memory-companion
  /// turn, distinct from ordinary companionship chat.
  memoryMoment,

  /// A turn inside the guided Mood Check-In conversation — see
  /// `PatientAiContext.moodCheckInActive`.
  moodCheckIn,

  /// Outside what the app knows about.
  outOfScope,
}

/// One earlier turn of this conversation, kept only for the length of the
/// session (not persisted) so the assistant can refer back to something said
/// a moment ago — "you just said her name was Ima" — without re-asking.
/// Long-term recall across *sessions* is a different mechanism: see
/// [SharedMemory] and `AppState.memoryFragments`.
@immutable
class ConversationTurn {
  const ConversationTurn({required this.fromUser, required this.text});

  final bool fromUser;
  final String text;
}

/// One patient-facing answer.
@immutable
class AssistantReply {
  const AssistantReply({
    required this.text,
    required this.intent,
    required this.source,
    this.suggestedActivity,
    this.followUps = const <String>[],
    this.sharedMemory,
    this.resurfacedFragmentId,
    this.moodCheckInDone = false,
    this.moodLevel,
  });

  /// Short, warm, and readable aloud. This is spoken to someone with memory
  /// difficulty, so it stays to a few short sentences.
  final String text;

  final AssistantIntent intent;
  final AiSource source;

  /// Set when the answer points at something the patient can start doing.
  final GameId? suggestedActivity;

  /// Two or three things they might ask next, offered as large tap targets
  /// rather than requiring typing.
  final List<String> followUps;

  /// Set only when this turn's message contained a genuine personal story —
  /// the app persists it as a new [MemoryFragment] via
  /// `AppState.saveSharedMemory`. Never set from a quiz answer or small talk.
  final SharedMemory? sharedMemory;

  /// Set when this turn gently reoffered a fragment the patient shared
  /// before — the app records the resurfacing via
  /// `AppState.markMemoryResurfaced`.
  final String? resurfacedFragmentId;

  /// True when this reply closes out a Mood Check-In conversation — the
  /// screen shows [text] as the closing message and its "talk more with
  /// Mitra" call to action, rather than asking the next question. Always
  /// false outside `PatientAiContext.moodCheckInActive`.
  final bool moodCheckInDone;

  /// The AI's gentle, non-diagnostic read of the patient's mood from a
  /// check-in conversation — only ever set alongside [moodCheckInDone].
  /// Never shown to the patient as a score; used to keep `AppState.mood`
  /// current and to give a doctor a one-glance summary next to the drawing.
  final MoodLevel? moodLevel;
}
