import 'dart:async';

import 'package:fllama/fllama.dart';

import '../models/daily.dart';
import 'ai_context.dart';
import 'ai_models.dart';
import 'ai_service.dart';
import 'model_download_service.dart';
import 'on_device_ai_service.dart';

/// Runs the fine-tuned "Mitra" Llama-3.2-1B model locally via `fllama`
/// (a Flutter binding to llama.cpp) — genuinely offline, no network call at
/// inference time. See `backend/training/` for how the model was trained and
/// `backend/SmaranSaathi.ipynb` for the export pipeline.
///
/// This is deliberately NOT a full replacement for [GeminiAiService]'s
/// structured JSON responses. The model was fine-tuned on short, plain-text
/// replies for a narrow persona (game feedback, weekly summaries, warm
/// companion turns) — it was never trained to produce the structured
/// intent/follow-ups/memory-sharing JSON Gemini's prompts ask for, and asking
/// a 1B model to do that reliably would be asking for trouble. So the design
/// is a hybrid:
///   - Fact-grounded answers (reminders, schedule, named family members) stay
///     100% on the deterministic [OnDeviceAiService] logic — never handed to
///     the model, which could plausibly invent a detail it wasn't trained on.
///   - Warm/conversational answers (companionship, orientation, activity
///     framing, out-of-scope redirects) get their `text` generated by the
///     model, with the surrounding structure (intent, follow-ups, suggested
///     activity) still coming from the same deterministic logic.
///   - `cognitiveInsight` and `dailyQuestions` currently stay on the
///     deterministic path — the app's live [CognitiveDomain] taxonomy
///     (memory/attention/reasoning/spatial/auditory/procedural) doesn't match
///     the simplified Memory/Focus/Speed framing the current training data
///     used, so wiring the model in here needs either a retrain against the
///     real taxonomy or a mapping layer. Tracked as a follow-up, not silently
///     faked.
///
/// Any failure — model not downloaded yet, device too old, a native-side
/// exception — falls back to the same [OnDeviceAiService] this class wraps,
/// so a caller can treat this exactly like any other [AiService] and never
/// see an error surface from it.
class LlamaOnDeviceAiService implements AiService {
  LlamaOnDeviceAiService({
    required this.modelDownload,
    OnDeviceAiService onDevice = const OnDeviceAiService(),
    this.maxTokens = 100,
    this.temperature = 0.7,
    this.contextSize = 512,
    this.timeout = const Duration(seconds: 30),
  }) : _onDevice = onDevice;

  final ModelDownloadService modelDownload;
  final OnDeviceAiService _onDevice;
  final int maxTokens;
  final double temperature;
  final int contextSize;
  final Duration timeout;

  /// Kept identical to `backend/training/train.py` / `eval_v3.py`'s SYSTEM —
  /// this is literally what the model was fine-tuned to answer under. Drift
  /// between this string and the training one silently degrades quality.
  static const String _systemPrompt =
      'You are Mitra, a gentle and warm AI companion for elderly patients with '
      'dementia. You analyse cognitive game metrics (Memory, Focus, Speed) and '
      'provide safe, warm, non-diagnostic feedback. Never give medical advice. '
      'When someone forgets a name, date, or fact, never suggest trying to recall, '
      'search for, or look it up — comfort them and offer a different calm '
      'activity instead.';

  /// Intents whose answer must stay grounded in real app data — never handed
  /// to the model, which wasn't trained on this person's actual reminders,
  /// schedule, or family and could plausibly invent a plausible-sounding one.
  ///
  /// [AssistantIntent.moodCheckIn] belongs here for a different reason: this
  /// model was never trained to produce the check-in's `moodCheckInDone`/
  /// `moodLevel` signal, and rebuilding an `AssistantReply` with only
  /// `text`/`intent`/`source`/`suggestedActivity`/`followUps` below would
  /// silently drop both — leaving the check-in screen with no way to ever
  /// see itself as finished.
  static const Set<AssistantIntent> _factGroundedIntents = <AssistantIntent>{
    AssistantIntent.reminders,
    AssistantIntent.schedule,
    AssistantIntent.people,
    AssistantIntent.moodCheckIn,
  };

  String? _modelPath;
  bool _checkedThisSession = false;

  /// Best-effort, cached-since-last-check status — for UI display (e.g. a
  /// settings screen showing "offline AI: ready" vs "not downloaded"), not
  /// relied on for correctness. `ask`/etc. always re-check via [_ensureReady].
  @override
  bool get isAvailable => _modelPath != null;

  Future<bool> _ensureReady() async {
    if (_modelPath != null) return true;
    if (_checkedThisSession) return false; // avoid re-hitting disk every call this session
    _checkedThisSession = true;
    _modelPath = await modelDownload.readyModelPath();
    return _modelPath != null;
  }

  /// Call after a fresh download completes so the next `ask` picks it up
  /// without waiting for the next cold check.
  void invalidateReadyCache() {
    _checkedThisSession = false;
    _modelPath = null;
  }

  @override
  void dispose() {}

  @override
  Future<AiResult<AssistantReply>> ask(String question, PatientAiContext context) async {
    final AssistantReply fallback = _onDevice.buildReply(question, context);

    if (_factGroundedIntents.contains(fallback.intent) || !await _ensureReady()) {
      return AiSuccess<AssistantReply>(fallback);
    }

    try {
      final String? generated =
          await _generate(question).timeout(timeout, onTimeout: () => null);
      final String text = (generated ?? '').trim();
      if (text.isEmpty) return AiSuccess<AssistantReply>(fallback);

      return AiSuccess<AssistantReply>(AssistantReply(
        text: text,
        intent: fallback.intent,
        source: AiSource.onDeviceLlm,
        suggestedActivity: fallback.suggestedActivity,
        followUps: fallback.followUps,
      ));
    } catch (_) {
      // Native-side failure (OOM, corrupt file, unsupported device) — the
      // rule-based answer is always safe to fall back to.
      return AiSuccess<AssistantReply>(fallback);
    }
  }

  // cognitiveInsight/dailyQuestions: see the class doc — deliberately still
  // deterministic until the domain-taxonomy mismatch is resolved.

  @override
  Future<AiResult<CognitiveInsight>> cognitiveInsight(PatientAiContext context) async =>
      AiSuccess<CognitiveInsight>(_onDevice.buildInsight(context));

  @override
  Future<AiResult<List<DailyQuestion>>> dailyQuestions(PatientAiContext context) async =>
      AiSuccess<List<DailyQuestion>>(_onDevice.buildDailyQuestions(context));

  Future<String?> _generate(String userText) {
    final String? path = _modelPath;
    if (path == null) return Future<String?>.value();

    final Completer<String?> completer = Completer<String?>();
    String latest = '';

    fllamaChat(
      OpenAiRequest(
        maxTokens: maxTokens,
        messages: <Message>[
          Message(Role.system, _systemPrompt),
          Message(Role.user, userText),
        ],
        modelPath: path,
        temperature: temperature,
        topP: 0.9,
        frequencyPenalty: 0,
        presencePenalty: 0,
        // 0 = CPU-only. Deliberately conservative: this needs to work on
        // whatever mid-range Android device a caregiver actually has, not
        // just ones with a capable mobile GPU.
        numGpuLayers: 0,
        contextSize: contextSize,
        logger: (String _) {},
      ),
      (String response, String openaiResponseJsonString, bool done) {
        latest = response;
        if (done && !completer.isCompleted) {
          completer.complete(latest);
        }
      },
    );

    return completer.future;
  }
}
