import 'package:flutter/material.dart';

/// The kind of medical document uploaded.
enum ReportKind { mri, eeg, bloodTest, other }

extension ReportKindX on ReportKind {
  String get label => switch (this) {
        ReportKind.mri => 'MRI Report',
        ReportKind.eeg => 'EEG Report',
        ReportKind.bloodTest => 'Blood Test',
        ReportKind.other => 'Other Report',
      };

  IconData get icon => switch (this) {
        ReportKind.mri => Icons.biotech_outlined,
        ReportKind.eeg => Icons.ssid_chart_rounded,
        ReportKind.bloodTest => Icons.opacity_rounded,
        ReportKind.other => Icons.description_outlined,
      };

  Color get color => switch (this) {
        ReportKind.mri => const Color(0xFF3F5B86),
        ReportKind.eeg => const Color(0xFF7A5680),
        ReportKind.bloodTest => const Color(0xFFC9694F),
        ReportKind.other => const Color(0xFF4A7FA5),
      };
}

/// Whether the AI has summarised this report.
enum ReportStatus { uploaded, summarised, awaitingDoctor }

extension ReportStatusX on ReportStatus {
  String get label => switch (this) {
        ReportStatus.uploaded => 'Uploaded',
        ReportStatus.summarised => 'AI summary ready',
        ReportStatus.awaitingDoctor => 'Awaiting doctor review',
      };
}

/// A medical document uploaded by the caregiver.
@immutable
class MedicalReport {
  const MedicalReport({
    required this.id,
    required this.kind,
    required this.dateLabel,
    required this.doctorName,
    required this.status,
    this.aiSummary,
    this.fileName = '',
  });

  final String id;
  final ReportKind kind;

  /// Human-readable date, e.g. "5 September 2025".
  final String dateLabel;
  final String doctorName;
  final ReportStatus status;

  /// Plain-language explanation generated by AI. Null when not yet generated.
  final String? aiSummary;
  final String fileName;

  bool get hasSummary => aiSummary != null && aiSummary!.isNotEmpty;
}

/// A single day's mood check-in used on the Wellbeing page.
@immutable
class MoodCheckIn {
  const MoodCheckIn({
    required this.dayLabel,
    required this.shortDay,
    required this.moodLabel,
    required this.moodEmoji,
    required this.moodColor,
    this.note = '',
  });

  final String dayLabel;
  final String shortDay;
  final String moodLabel;
  final String moodEmoji;
  final Color moodColor;
  final String note;
}
