import 'package:flutter/foundation.dart';

import 'daily.dart';

/// One question-and-answer exchange from the check-in conversation phase.
///
/// The first turn's [question] is always the fixed opening line ("How are
/// you feeling right now?"); every one after that is generated by the AI
/// layer from the previous [answer] — see `PatientAiContext.moodCheckInActive`
/// and the "MOOD CHECK-IN MODE" section of the Gemini prompt. Kept as its own
/// small record (not folded into [ConversationTurn]) because a doctor reading
/// this later needs the question a reply was answering, not just a flat list
/// of lines.
@immutable
class MoodCheckInTurn {
  const MoodCheckInTurn({required this.question, required this.answer});

  final String question;
  final String answer;
}

/// One saved Mood Check-In: a drawing, and the short guided conversation that
/// followed it.
///
/// Deliberately not a [GameSession]/[GamePerformance] — those are shaped for
/// a numeric 0-100 score, and neither free drawing nor a feelings check-in has
/// one to report honestly. This is its own small record: an image, what was
/// said, a gentle non-diagnostic mood read, and whatever a doctor later
/// chooses to say about it.
@immutable
class MoodDrawing {
  const MoodDrawing({
    required this.id,
    required this.dayOffset,
    required this.timeLabel,
    required this.pngBytes,
    this.transcript = const <MoodCheckInTurn>[],
    this.moodLevel,
    this.doctorNote,
    this.notedAtIso,
    this.notedBy,
  });

  final String id;

  /// 0 = today, 1 = yesterday … matches [GameSession.dayOffset]'s convention.
  final int dayOffset;
  final String timeLabel;
  final Uint8List pngBytes;

  /// The check-in conversation that followed the drawing, oldest first. Empty
  /// for a drawing saved before this phase existed, or if the patient closed
  /// out before answering the opening question.
  final List<MoodCheckInTurn> transcript;

  /// The AI's gentle, non-diagnostic read of the conversation — never shown
  /// to the patient as a score, only used to keep `AppState.mood` current and
  /// to give the doctor a one-glance summary alongside the transcript.
  final MoodLevel? moodLevel;

  /// A doctor's own freeform clinical note about this drawing — never
  /// generated automatically. One note per drawing; saving again overwrites
  /// it, the same shape as `CaregiverObservation.note`.
  final String? doctorNote;
  final String? notedAtIso;
  final String? notedBy;

  bool get hasNote => doctorNote != null && doctorNote!.trim().isNotEmpty;

  MoodDrawing copyWith({
    String? doctorNote,
    String? notedAtIso,
    String? notedBy,
  }) =>
      MoodDrawing(
        id: id,
        dayOffset: dayOffset,
        timeLabel: timeLabel,
        pngBytes: pngBytes,
        transcript: transcript,
        moodLevel: moodLevel,
        doctorNote: doctorNote ?? this.doctorNote,
        notedAtIso: notedAtIso ?? this.notedAtIso,
        notedBy: notedBy ?? this.notedBy,
      );
}
