"""Pydantic schemas for Telehealth Video Consultations, AI Clinical Notes, and Chat."""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class CallStatus(str, Enum):
    INITIATED = "initiated"
    RINGING = "ringing"
    CONNECTED = "connected"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


class ClinicalSoapNote(BaseModel):
    """Structured SOAP note generated by AI Clinical Scribe."""
    subjective: str = Field(..., description="Patient complaints, symptoms, caregiver observations")
    objective: str = Field(..., description="Clinician observations, alertness, cognitive response latency")
    assessment: str = Field(..., description="Cognitive stability or variation, emotional state assessment")
    plan: str = Field(..., description="Clinical recommendations, lifestyle changes, follow-up timeline")
    prescriptions: List[str] = Field(default_factory=list, description="Recommended medications or adjustments")
    suggested_exercises: List[str] = Field(default_factory=list, description="Targeted cognitive games or memory tasks")


class PatientMitraSummary(BaseModel):
    """Empathetic, clear summary crafted for the patient and family caregiver."""
    title: str = Field("Consultation Care Summary", description="Summary title")
    key_takeaways: List[str] = Field(default_factory=list, description="Actionable points in plain language")
    medication_reminders: List[str] = Field(default_factory=list, description="Clear medicine instructions")
    daily_routine_advice: str = Field("", description="Gentle tips for daily routine and well-being")
    next_checkup: str = Field("In 2 weeks", description="Next follow-up date or timeframe")


class ConsultationSession(BaseModel):
    """A record of a completed or ongoing teleconsultation."""
    id: str
    doctor_id: str
    patient_id: str
    patient_name: str
    room_name: str
    status: CallStatus = CallStatus.COMPLETED
    started_at: datetime = Field(default_factory=datetime.utcnow)
    ended_at: Optional[datetime] = None
    duration_seconds: int = 0
    transcript: Optional[str] = None
    soap_note: Optional[ClinicalSoapNote] = None
    patient_summary: Optional[PatientMitraSummary] = None
    doctor_approved: bool = False


class CallInitiateRequest(BaseModel):
    doctor_id: str
    patient_id: str
    patient_name: str
    caller_role: str = "doctor"  # "doctor" or "patient"


class CallInitiateResponse(BaseModel):
    session_id: str
    room_name: str
    signaling_ws_url: str
    status: CallStatus


class SummarizeCallRequest(BaseModel):
    session_id: Optional[str] = None
    doctor_id: str = "doc_001"
    patient_id: str = "pat_001"
    patient_name: str = "Ramesh Kumar"
    transcript: str = Field(..., description="Full consultation dialogue / transcript")
    language: str = "English"


class SummarizeCallResponse(BaseModel):
    session_id: str
    soap_note: ClinicalSoapNote
    patient_summary: PatientMitraSummary
    generated_at: datetime = Field(default_factory=datetime.utcnow)


class ChatMessageSchema(BaseModel):
    id: str
    doctor_id: str
    patient_id: str
    sender_id: str
    sender_role: str  # "doctor" or "patient"
    sender_name: str
    content: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    is_read: bool = False


class SendMessageRequest(BaseModel):
    doctor_id: str
    patient_id: str
    sender_id: str
    sender_role: str
    sender_name: str
    content: str
